### ISSUE TITLE
Question: Unclear how to call Lua functions from JavaScript or vice versa?

### ISSUE THREAD

**Issue by trentapple** [PaulBernier/castl#10]
Is it possible to invoke / call Lua any function from the JavaScript code? If so, how do you call a Lua function and make use of anything it returns?

**Comment by PaulBernier** [comment]
It's technically possible. The tricky part is that all JS functions transpiled to Lua have a first 'this' parameter, and so every call to a function also pass a 'this' context as a first argument. Which means that your Lua function that you are planning to use, and that has not been transpiled from JavaScript, will have to take that into account and have a dummy 'this' first parameter. So it depends if you have control over definition of the Lua functions you are trying to call.
Let me know if it's unclear, and may be provide me with an example for more insight on your use case. (where does the JS code comes from, where does the Lua function you want to invoke comes from... depending on what you control, it may be more or less doable.)

**Comment by trentapple** [comment]
That isn't too bad because if I wrote the Lua function in an "OO esque" format, the first parameter that the Lua function would expect is "self" (although this is usually hidden by syntactic sugar). Interesting...

I don't have much control over the Lua functions since it is crippled-down Lua v5.1 (embedded into a game for addon development only).

Thanks!
