### ISSUE TITLE
Is it possible to remove the import of the runtime library?

### ISSUE THREAD

**Issue by DenLilleMand** [PaulBernier/castl#27]
The transpiler inserts a import of `castl.runtime` at the top and uses _ENV in alot of places, is it possible to get rid of this ? the environment where i do these things i don't need the extra dependencies, it will already be a sort of controlled environment, just need the syntax

**Comment by PaulBernier** [comment]
In short, no, you need that runtime. The runtime contains the implementation of many core JS structures, functions and operators in Lua in order to reproduce JS behavior (You can see those [here](https://github.com/PaulBernier/castl/blob/master/lua/castl/runtime.lua#L46)).

**Comment by DenLilleMand** [comment]
> In short, no, you need that runtime. The runtime contains the implementation of many core JS structures, functions and operators in Lua in order to reproduce JS behavior (You can see those [here](https://github.com/PaulBernier/castl/blob/master/lua/castl/runtime.lua#L46)).

Arg i see, i guess i underestimated the complexity of transpiling JS to Lua
