### ISSUE TITLE
Guide for transpiling bigger babel based js projects

### ISSUE THREAD

**Issue by ruslantalpa** [PaulBernier/castl#6]
What would be the general steps in transpiling a bigger project like https://github.com/graphql/graphql-js
Would it be enough to change [this line](https://github.com/PaulBernier/castl/blob/master/bin/castl.js#L146) in order to have the basis for converting most of the project?
Is the idea to transpile one file at a time (using some bash script to automate)
Although not an expert in any of the languages i am comfortable with changing any part (modify/anotate the js project, modify castle code).

Thank you

**Comment by PaulBernier** [comment]
Hi,
An idea to transpile a whole project would be to bundle it (browserify, webpack...) and then transpile the single file. Technically I believe it should work but I cannot guarantee it. Also I see that graphql use ES6 import/export system and I don't know if bundlers play smooth with this.
