### ISSUE TITLE
SyntaxError: Couldn't transpile JS code: Error: Couldn't find preset "es2015" relative to directory "."

### ISSUE THREAD

**Issue by akiratsai** [PaulBernier/castl#9]
When I try to transpile my ES6 code, I got the error message saying that

> SyntaxError: Couldn't transpile JS code: Error: Couldn't find preset "es2015" relative to directory "."

Then I try to solve this problem by using [this solution](https://github.com/babel/gulp-babel/issues/93#issuecomment-249172581)

And I try to revise the code from `"presets": ["es2015"]` to `"presets": ['babel-preset-es2015'].map(require.resolve)`

And which was introduced from [here](https://github.com/PaulBernier/castl/commit/0fa43a9411cf707019fb403fb4350c837f05b88a#diff-5d2f3a8e861840af6aec62b1a13a7caaR147)

And it works

**Comment by PaulBernier** [comment]
Thanks for reporting, and providing a solution! This is fixed by a152067bde6ecb4ebd123cc7be0d6f8d7498352e I also added the preset for es2016 and es2017 at the same time.
